generatorName: go-server-gin
outputDir: samples/server/petstore/go/server/gin
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/go-server-gin
additionalProperties:
  hideGenerationTimestamp: "true"
